services:
  - name: meu-app
    type: web
    runtime: python
    repo: https://github.com/seu-usuario/meu-app
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:5000 app:app"
    envVars:
      - key: DATABASE_PATH
        value: "/data/orcamentos.db"
    disk:
      name: sqlite_volume
      mountPath: "/data"
      sizeGB: 1

